[package]
name = "fast_query_parser"
version = "0.1.0"
edition = "2021"

[lib]
name = "fast_query_parser"
crate-type = ["cdylib"]

[dependencies]
percent-encoding = "2.2.0"
pyo3 = { version = "0.17.3", features = ["extension-module"] }
pythonize = "0.17.0"
serde = "1.0.151"
serde_json = "1.0.90"
